[package]
name = "nuros-agent"
version = "0.1.0"
authors = ["Nuros"]
edition = "2021"


[dependencies]
ureq = { version = "2.9", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
