name: Deploy Nuros Grid
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - run: npm ci
      - run: npm run build

      - run: npm i -g wrangler

      - name: Put Worker secrets
        run: |
          wrangler secret put UPSTASH_REDIS_REST_URL --value "${{ secrets.UPSTASH_REDIS_REST_URL }}"
          wrangler secret put UPSTASH_REDIS_REST_TOKEN --value "${{ secrets.UPSTASH_REDIS_REST_TOKEN }}"
          wrangler secret put AGENT_ADMIN_KEY --value "${{ secrets.AGENT_ADMIN_KEY }}"
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Publish Worker
        run: npx wrangler deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

  deploy-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build
      - name: Publish Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: nuros-grid-web
          directory: ./out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
